### ISSUE TITLE
loop in and out shifted upwards one row in TALL (defualt tall) mode

### ISSUE THREAD

**Issue by robenimmersatt** [szdavid92/mixxx-launchpad#11]
So loop IN and OUT is on the same buttons as LOOP and SLIP, and the buttons below are not assigned. This is only an issue in the default tall layout.

**Comment by szdavid92** [comment]
Hi, sorry for getting back to you so late with this. Yes, it seems [this](https://github.com/szdavid92/mixxx-launchpad/blob/master/packages/app/src/App/presets/Tall.js#L45) should be at position `3, 3`. I am going to fix later today, thanks for reporting.

**Comment by Swiftb0y** [comment]
Since you fixed said you will fix this. There is no need for a PR.
The only other Issue I found is that the Playlist buttons don't get unmounted which should probably be done [here](https://github.com/szdavid92/mixxx-launchpad/blob/master/packages/app/src/App/PlaylistSidebar.js#L51). The rest of the mapping works flawless.

**Comment by szdavid92** [comment]
There's a problem with dismounting the layout, and the rest of the code is not called. I reordered the dismounts as a workaround, but we'll need a proper solution.

**Comment by szdavid92** [comment]
fixed in https://github.com/szdavid92/mixxx-launchpad/releases/tag/v2.1.6
